version: '3.9'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - ./src:/app/src
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=api
      - MYSQL_USER=api
      - MYSQL_PASSWORD=123456
    container_name: db
    volumes:
      - ./db-data:/var/lib/mysql:z
    # ports:
    #   - 3306:3306
  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080

volumes:
  db-data:

